---
- name: Ensure certbot image is present.
  become_user: "{{ nc_user }}"
  containers.podman.podman_image:
    name: "{{ certbot_image }}"
    state: present
    force: "{{ update_images }}"
    tag: "latest"

- name: Ensure directories exist for certbot volumes.
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ nc_user }}"
    group: "{{ nc_user }}"
  loop:
    - "{{ certbot_certs_dir }}"
    - "{{ certbot_log_dir }}"
    - "{{ certbot_lib_dir }}"
    - "{{ certbot_www_dir }}"

- name: Update volumes list for nginx.
  ansible.builtin.set_fact:
    nginx_volumes: '{{ nginx_volumes + certbot_nginx_volumes }}'

- name: Copy http configuration template.
  become_user: "{{ nc_user }}"
  ansible.builtin.template:
    src: templates/nginx/certbot.http.nginx.conf.j2
    dest: "{{ nginx_conf_path }}/{{ certbot_server_name }}.http.conf"
    mode: "0644"
    force: true
  changed_when: true
  notify: Recreate nginx.

- name: Flush handlers.
  ansible.builtin.meta: flush_handlers

- name: Ensure certbot is started to obtain certificates.
  become_user: "{{ nc_user }}"
  containers.podman.podman_container:
    name: certbot
    image: "{{ certbot_image }}"
    state: started
    rm: true
    recreate: true
    volumes: "{{ certbot_volumes }}"
    command: >
      certonly -n --webroot
      --webroot-path /tmp/letsencrypt
      -m {{ certbot_email }}
      --agree-tos
      -d {{ certbot_server_name }}

- name: Copy https configuration template.
  become_user: "{{ nc_user }}"
  ansible.builtin.template:
    src: templates/nginx/certbot.https.nginx.conf.j2
    dest: "{{ nginx_conf_path }}/{{ certbot_server_name }}.https.conf"
    mode: "0644"
    force: true
  changed_when: true
  notify: Reload nginx.
