---
- name: Ensure app container image is present.
  become_user: "{{ nc_user }}"
  containers.podman.podman_image:
    name: "{{ nc_app_image }}"
    state: present
    force: "{{ update_images }}"
    tag: "latest"

- name: Ensure app volume directories exist with correct ownership.
  become: true
  ansible.builtin.file:
    path: "{{ nc_volumes_dir }}/{{ item.dir }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
    state: directory
  loop:
    - { dir: "app", owner: "{{ nc_app_user_id }}", mode: "755"}
    - { dir: "config", owner: "{{ nc_app_user_id }}", mode: "755"}
    - { dir: "data", owner: "{{ nc_app_user_id }}", mode: "770"}

- name: Ensure app container exists.
  become_user: "{{ nc_user }}"
  containers.podman.podman_container:
    pod: "{{ nc_pod_name }}"
    name: "{{ nc_pod_name }}-app"
    image: "{{ nc_app_image }}"
    state: created
    detach: true
    restart_policy: "on-failure"
    volumes:
      - "{{ nc_volumes_dir }}/app:/var/www/html:Z"
      - "{{ nc_volumes_dir }}/config:/var/www/html/config:Z"
      - "{{ nc_volumes_dir }}/data:/var/www/html/data:Z"
    env:
      MYSQL_HOST: 127.0.0.1
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      NEXTCLOUD_ADMIN_USER: "{{ nextcloud_admin_user }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "{{ nextcloud_trusted_domains }}"
      OVERWRITEPROTOCOL: "{{ nextcloud_overwriteprotocol }}"
      OVERWRITECLIURL: "{{ nextcloud_overwritecliurl }}"
      SMTP_HOST: "{{ smtp_host }}"
      SMTP_SECURE: "{{ smtp_secure }}"
      SMTP_PORT: "{{ smtp_port }}"
      SMTP_AUTHTYPE: "{{ smtp_authtype }}"
      SMTP_NAME: "{{ smtp_name }}"
      SMTP_PASSWORD: "{{ smtp_password }}"
      MAIL_FROM_ADDRESS: "{{ mail_from_address }}"
      MAIL_DOMAIN: "{{ mail_domain }}"
