---
- name: Ensure app container exists.
  containers.podman.podman_container:
    pod: "{{ pod_name }}"
    name: "{{ pod_name }}-app"
    image: "{{ image_name_nextcloud }}"
    state: created
    detach: true
    restart_policy: "on-failure"
    volumes:
      - "{{ volumes_dir }}/app:/var/www/html:Z"
      - "{{ volumes_dir }}/config:/var/www/html/config:Z"
      - "{{ volumes_dir }}/data:/var/www/html/data:Z"
    env:
      MYSQL_HOST: 127.0.0.1
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_DATABASE: "{{ mysql_database }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      NEXTCLOUD_ADMIN_USER: "{{ nextcloud_admin_user }}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{ nextcloud_admin_password }}"
      NEXTCLOUD_TRUSTED_DOMAINS: "{{ nextcloud_trusted_domains }}"
      OVERWRITEPROTOCOL: "{{ nextcloud_overwriteprotocol }}"
      OVERWRITECLIURL: "{{ nextcloud_overwritecliurl }}"
      SMTP_HOST: "{{ smtp_host }}"
      SMTP_SECURE: "{{ smtp_secure }}"
      SMTP_PORT: "{{ smtp_port }}"
      SMTP_AUTHTYPE: "{{ smtp_authtype }}"
      SMTP_NAME: "{{ smtp_name }}"
      SMTP_PASSWORD: "{{ smtp_password }}"
      MAIL_FROM_ADDRESS: "{{ mail_from_address }}"
      MAIL_DOMAIN: "{{ mail_domain }}"
