---
# nextcloud/tasks/backup.yml
- name: Ensure restic is installed.
  become: true
  ansible.builtin.dnf:
    name: restic
    state: present

- name: Check if restic repository already exists.
  ansible.builtin.stat:
    path: "{{ backup_dir }}/{{ pod_name }}"
  register: out_repo

- name: Attempt to initialize a repository.
  when: not out_repo.stat.exists
  block:
    - name: Ensure backup directory exists.
      become: true
      ansible.builtin.file:
        path: "{{ backup_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    - name: Ensure a password file exists.
      ansible.builtin.copy:
        content: "{{ restic_password }}"
        dest: "{{ restic_password_file }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0600"

    - name: Ensure a restic repository has been initialized.
      ansible.builtin.command:
        cmd: "restic init"
      changed_when: true
      environment:
        RESTIC_REPOSITORY: "{{ backup_dir }}/{{ pod_name }}"
        RESTIC_PASSWORD_FILE: "{{ restic_password_file }}"

- name: Install a helper script for restic-{{ pod_name }}.
  become: true
  ansible.builtin.template:
    src: templates/restic-helper.j2
    dest: "{{ restic_helper }}"
    mode: "0700"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Ensure a logging directory exists.
  become: true
  ansible.builtin.file:
    path: "{{ volumes_dir }}/log"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Install a file in logrotate.d.
  become: true
  ansible.builtin.template:
    src: templates/logrotate.j2
    dest: /etc/logrotate.d/{{ pod_name }}-backup
    mode: "0644"

- name: Copy backup script.
  become: true
  ansible.builtin.template:
    src: templates/pod-backup.j2
    dest: /usr/local/bin/{{ pod_name }}-backup
    mode: "0700"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Copy systemd units.
  ansible.builtin.template:
    src: templates/{{ item.src }}
    dest: /home/{{ ansible_user }}/.config/systemd/user/{{ item.dest }}
    mode: "0644"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - src: pod-backup.service.j2
      dest: "{{ pod_name }}-backup.service"
    - src: pod-backup.timer.j2
      dest: "{{ pod_name }}-backup.timer"

- name: Install systemd timer.
  ansible.builtin.systemd:
    name: "{{ pod_name }}-backup.timer"
    state: started
    enabled: true
    scope: user
    daemon-reload: true
