---
- name: Ensure podman is installed.
  ansible.builtin.dnf:
    name: podman
    state: present
  become: true

- name: Ensure volume directories exist and have correct ownership.
  ansible.builtin.file:
    path: "{{ volumes_dir }}/{{ item.dir }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    mode: "{{ item.mode }}"
    state: directory
  loop:
    - { dir: "db", owner: "100998", mode: "0755"}
    - { dir: "app", owner: "100032", mode: "755"}
    - { dir: "config", owner: "100032", mode: "755"}
    - { dir: "data", owner: "100032", mode: "770"}
  become: true

- name: Ensure a pod exists for {{ pod_name }}.
  containers.podman.podman_pod:
    name: "{{ pod_name }}"
    state: created
    publish: "{{ pod_http_port }}:80"

- name: Import db container tasks.
  ansible.builtin.import_tasks: db.yml

- name: Import app container tasks.
  ansible.builtin.import_tasks: app.yml

- name: Import systemd tasks.
  ansible.builtin.import_tasks: systemd.yml

- name: Import nginx proxy tasks.
  ansible.builtin.import_tasks: nginx.yml
  when: use_tailscale or use_letsencrypt

- name: Import backup tasks.
  ansible.builtin.import_tasks: backup.yml
