---
- name: Ensure podman is installed.
  become: true
  ansible.builtin.dnf:
    name: podman
    state: present

- name: Import nginx tasks.
  ansible.builtin.import_tasks: nginx/main.yml
  when: nginx_use_nginx

- name: Fail
  ansible.builtin.fail:
    msg: Break

- name: Import pod tasks.
  ansible.builtin.import_tasks: pod.yml

- name: Import db container tasks.
  ansible.builtin.import_tasks: db.yml

- name: Import app container tasks.
  ansible.builtin.import_tasks: app.yml

- name: Import systemd tasks.
  ansible.builtin.import_tasks: systemd.yml

- name: Import backup tasks.
  ansible.builtin.import_tasks: backup.yml
