---
- name: Check if user has lingering enabled.
  ansible.builtin.command:
    cmd: "ls /var/lib/systemd/linger"
  changed_when: false
  register: linger

- name: Enable linger for user {{ user }}
  become: true
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ user }}"
  changed_when: true
  when: "user not in linger.stdout"

- name: Generate systemd units for {{ pod_name }}.
  become_user: "{{ user }}"
  containers.podman.podman_generate_systemd:
    name: "{{ pod_name }}"
    dest: "/home/{{ user }}/.config/systemd/user/"
    requires: "{{ pod_systemd_requires }}"
    after: "{{ pod_systemd_after }}"
    restart_policy: "on-failure"

- name: Ensure systemd units are started and enabled for {{ pod_name }}.
  become_user: "{{ user }}"
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true
    name: "pod-{{ pod_name }}"
    enabled: "{{ pod_systemd_enabled }}"
    state: started

- name: Ensure systemd service is copied for nextcloud cron job.
  become_user: "{{ user }}"
  ansible.builtin.template:
    src: templates/cron-app.service.j2
    dest: /home/{{ user }}/.config/systemd/user/{{ pod_name }}-cron-app.service
    mode: "644"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Ensure systemd timer is copied for nextcloud cron job.
  become_user: "{{ user }}"
  ansible.builtin.template:
    src: templates/cron-app.timer.j2
    dest: /home/{{ user }}/.config/systemd/user/{{ pod_name }}-cron-app.timer
    mode: "644"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Ensure systemd timer and service are stared and enabled for nextcloud cron job.
  become_user: "{{ user }}"
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true
    name: "{{ pod_name }}-cron-app.timer"
    enabled: true
    state: started
