---
- name: Check if user has lingering enabled.
  ansible.builtin.command:
    cmd: "ls /var/lib/systemd/linger"
  changed_when: false
  register: linger

- name: Enable linger for user {{ ansible_user_id }}
  become: true
  ansible.builtin.command:
    cmd: "loginctl enable-linger {{ ansible_user_id }}"
  changed_when: true
  when: "ansible_user_id not in linger.stdout"

- name: Generate systemd units for {{ pod_name }}.
  containers.podman.podman_generate_systemd:
    name: "{{ pod_name }}"
    dest: "/home/{{ ansible_user_id }}/.config/systemd/user/"
    restart_policy: "on-failure"

- name: Require mounts in systemd unit for {{ pod_name }}.
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.config/systemd/user/pod-{{ pod_name }}.service"
    state: present
    regexp: '^RequiresMountsFor='
    line: 'RequiresMountsFor={{ volumes_dir }}/data'

- name: Ensure systemd units are started and enabled for {{ pod_name }}.
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true
    name: "pod-{{ pod_name }}"
    enabled: true
    state: started

- name: Ensure systemd service is copied for nextcloud cron job.
  ansible.builtin.template:
    src: templates/cron-app.service.j2
    dest: /home/{{ ansible_user_id }}/.config/systemd/user/{{ pod_name }}-cron-app.service
    mode: "644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Ensure systemd timer is copied for nextcloud cron job.
  ansible.builtin.template:
    src: templates/cron-app.timer.j2
    dest: /home/{{ ansible_user_id }}/.config/systemd/user/{{ pod_name }}-cron-app.timer
    mode: "644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Ensure systemd timer and service are stared and enabled for nextcloud cron job.
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true
    name: "{{ pod_name }}-cron-app.timer"
    enabled: true
    state: started
