- name: Generate SSL certificates with tailscale.
  become: true
  ansible.builtin.command:
    cmd: >
      tailscale cert
      --cert-file /etc/tailscale/{{ pod_name }}.crt
      --key-file /etc/tailscale/{{ pod_name }}.key
      {{ server_name }}
    creates: "/etc/tailscale/{{ pod_name }}.*"
  notify: Restart nginx.

- name: Copy configuration template.
  become: true
  ansible.builtin.template:
    src: templates/tailnet.nginx.conf.j2
    dest: /etc/nginx/conf.d/{{ pod_name }}.conf
    mode: "0644"
  notify: Restart nginx.
