---
# handlers file for nextcloud
- name: Wait to initialize db.
  ansible.builtin.wait_for:
    timeout: 10

- name: Restart nginx.
  containers.podman.podman_container:
    name: nginx
    state: restarted

- name: Reload nginx.
  become_user: "{{ nc_user }}"
  ansible.builtin.command:
    cmd: podman exec nginx nginx -s reload
  changed_when: true

- name: Recreate nginx.
  ansible.builtin.include_tasks: tasks/nginx/setup.yml
