---
- name: Converge
  hosts: all

  vars:
    use_tailscale: false

  tasks:
    - name: Setup Tailscale
      when: use_tailscale
      block:
        - name: Setup Tailscale
          ansible.builtin.include_role:
            name: tailscale

        - name: Copy ssl certificates.
          become: true
          ansible.builtin.copy:
            src: "{{ item.src }}"
            dest: "/etc/nginx/"
            mode: "{{ item.mode }}"
          loop:
            - { src: files/nc.key, mode: "0600" }
            - { src: files/nc.crt, mode: "0644" }

    - name: "Include palekiwi.nextcloud"
      ansible.builtin.include_role:
        name: "palekiwi.nextcloud"
      vars:
        backup_systemd_requires:
          - mnt-backup.mount
        backup_systemd_after:
          - mnt-backup.mount
